algolia/algoliasearch-helper-flutter

helper_dart/lib/src/query_builder.dart
Set `objectID` to `attributesToRetrieve` and `attributesToHighlight` in auxiliary queries generated by `QueryBuilder` to workaround the community client exception.
=> fix(queryBuilder): add objectID to attributes for aux queries

helper_dart/lib/src/hits_searcher.dart
Remove `distinct` from search state stream.
=> fix(HitsSearcher): re-run search with same state

helper_dart/lib/src/highlighting.dart
Make parameters of `Hit.getHighlightedString` named to ensure better DX.
=> fix: Make parameters of `Hit.getHighlightedString` named

helper_dart/lib/src/filters.dart
Type aliasing `StatelessFilters` to `ImmutableFilters` to avoid API breaking changes and keep backward compatibility.
=> fix: deprecated `ImmutableFilters`

helper_dart/lib/src/hits_searcher.dart
| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no    
| BC breaks?        | no
| Related Issue     | [FX-1955](https://algolia.atlassian.net/browse/FX-1955)
| Need Doc update   | no
---
Allow to use the same search state to run a search query. Useful to retry a search operation in case of a failure.
Distinct search operations can be implemented at text input level. Debounce will still discard repeated entries in the specified timeframe.
=> fix(searcher): same search query

helper_dart/lib/src/hits_searcher.dart, helper_dart/lib/src/search_request.dart, helper_dart/test/hits_searcher_test.dart
| New feature?    | yes   |
| Related Issue   | FX-2128 |
- Add `rerun` search query capability
- Reverts back distinct search operations behavior
=> feat: add rerun search query

helper_dart/lib/src/disposable.dart, insights_dart/pubspec.lock, insights_dart/pubspec.yaml, melos.yaml
| Bug fix?        | yes
Some fixes to make `analyze` check pass.
Add missing `lint:pub` definition in `melos.yaml` file.
The code passes all CI checks
=> fix: analyze issues

helper_flutter/pubspec.yaml
| Related Issue   | Fix #80 
Bumps `algolia_helper` in the `algolia_helper_flutter` to 0.3.1
Outdated `algolia_helper` version (0.2.3) in the `algolia_helper_flutter` pubspec.
=> fix(dependency): outdated algolia_helper version in the algolia_helper_flutter pubspec

helper/lib/algolia_helper_flutter.dart
| Related Issue   | Fix #... |
Adds export of `facet.dart` so the `Facet` class is visible to the compiler which allows code with `Facet` type annotation to work.
The `Facet` class wasn't exported which resulted in the compiler not finding it when making type annotations. An example of this would be in the `Getting started` guide in [this section](https://www.algolia.com/doc/guides/building-search-ui/getting-started/flutter/#implement-results-filtering) for `body: StreamBuilder<List<SelectableItem<Facet>>>(`. The code there doesn't compile without the export.
=> fix(facet): export facet model

helper/lib/src/facet_list.dart, insights/lib/src/algolia_event_service.dart, insights/test/event_test.dart
| Related Issue   | Fix #108  |
Add missing filter attribute for Insights click event in the FacetList
Exception thrown due to wrong `filter` value.
=> fix(facetlist): add missing filter attribute for insights event

helper/lib/src/model/search_state.dart, helper/lib/src/service/algolia_hits_search_service.dart, helper/pubspec.yaml, insights/pubspec.yaml
| BC breaks?      | yes       |
| Related Issue   | Fix #111 |
Bump Dart client dependency version to stable one, few implementation adjustments.
- Change type of `insideToBoundingBox` from `List<double>` to `List<List<double>>` to match the update on the Dart Client side
- Update `_disjunctiveSearch` implementation of the `AlgoliaHitsSearchService` using the common `search` method.
Preparation for stable release of helper library
=> chore(client): bump to stable version

helper/lib/src/searcher/hits_searcher.dart, helper/test/facet_list_test.dart
| Related Issue   | Fix #124 |
I removed the restriction to define the EventTracker and added an unit test to cover that case
esentially when you need to initialize the FacetList the getter breaks the code, however, looking in the code is expected the null value.
=> fix(HitsSearcher): non-initialized EventTracker

helper/lib/algolia_helper_flutter.dart, helper/lib/src/client_options.dart, helper/lib/src/searcher/hits_searcher.dart, helper/lib/src/service/algolia_hits_search_service.dart
| Related Issue   | CR-5915 |
Add `ClientOptions` parameter, enabling HTTP client configuration.
=> feat(searcher): add client options

helper/example/facet_list.dart, helper/example/facet_list_app.dart, helper/lib/src/searcher/facet_searcher.dart, helper/lib/src/searcher/multi_searcher.dart, helper/lib/src/service/algolia_facet_search_service.dart, helper/lib/src/service/algolia_hits_search_service.dart, helper/lib/src/service/algolia_multi_search_service.dart, helper/lib/src/service/client_options.dart
| Related Issue   | n/a |
[#131](https://github.com/algolia/algoliasearch-helper-flutter/pull/131) adds `ClientOptions`  to `HitsSearcher`.
In this PR we add `ClientOptions` to `MultiSearcher` and `FacetSearcher`
=> feat(searcher): add `ClientOptions` to `MultiSearcher` and `FacetSearcher`

helper/lib/src/facet_list.dart, helper/lib/src/searcher/facet_searcher.dart, helper/lib/src/searcher/hits_searcher.dart
| Bug fix?        |     no   |
| New feature?    |     no   |
| Related Issue   |          |
| Need Doc update |     no   |
This PR calls `dispose()` instead of `cancel()` on CompositeSubscriptions, to pass pana checks during CI.
pana checks for issues when dependencies are using downgraded versions, and in this case fails the check for the following reasons:
```
[algolia_helper_flutter]:  - `UNDEFINED_METHOD` - `lib/src/facet_list.dart:297:20` - The method 'cancel' isn't defined for the type 'CompositeSubscription'.
[algolia_helper_flutter]:  - `UNDEFINED_METHOD` - `lib/src/searcher/facet_searcher.dart:289:20` - The method 'cancel' isn't defined for the type 'CompositeSubscription'. …
```
=> ci: use downgrade-safe method to dispose of subscriptions

helper/pubspec.yaml, pubspec.yaml
| Related Issue   |  |
This PR updates melos to the latest version and changes how algolia_insights is constrained in algolia_helper_flutter's dependency file. The constraint is the same, but the updated notation does not cause issues with `melos version` anymore.
=> chore: update melos and change linked insights version notation

.github/workflows/publish.yml
| Related Issue   | Fix #... |
This PR:
- updates the dart action path to work properly
- delays publishing the helper in order to give more time for the insights package to be on pub.dev
=> ci: publish helper after insights

helper/lib/src/filter_group_converter.dart, helper/lib/src/service/algolia_client_extensions.dart, helper/test/filter_converter_test.dart, insights/lib/src/algolia_event_service.dart
| Bug fix?        | yes      |
| New feature?    |     no   |
| Related Issue   | Fix #151 |
| Need Doc update |     no   |
This PR removes an invalid search parameters applied to `SearchForHits`. The typing has been removed in algoliasearch-client-dart@1.27.2, preventing users from building their implementation when updating to this version.
=> fix(client): remove invalid `maxFacetHits` in `SearchForHits` extension

helper/lib/src/client_options.dart, helper/lib/src/service/client_options.dart
| New feature?    | yes   |
| Related Issue   | Fix #148  |
This change enable to pass a custom interceptor do ClientOptions
This way I be enabled to create my own interceptor as CacheInterceptor
=> feat(clientOption): enable pass interceptor as parameters

helper/lib/src/searcher/multi_searcher.dart, helper/test/multi_searcher_test.dart
| Bug fix?        | yes  |
| New feature?    |no   |
| Related Issue   | [CR-8778] |
| Need Doc update |no   |
forward the error from all streams in multi searcher
allows you to listen to errors like you can with a hits searcher
[CR-8778]: https://algolia.atlassian.net/browse/CR-8778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(multiSearcher): forward error

insights/lib/src/insights.dart
| Bug fix?        | yes  |
| Related Issue   | [CR-9049](https://algolia.atlassian.net/browse/CR-9049) |
Seems like a problem with copy/pasting, variable shadowing and lack of linting tools.
Still named the variable the same as for other methods even if it shadows the upper scope `objectIDs` array.
Events were split but sent the whole objectIDs array, causing an error
[CR-9049]: https://algolia.atlassian.net/browse/CR-9049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(insights): properly divide viewed objects events
