algolia/algoliasearch-helper-flutter

helper_dart/README.md, helper_flutter/README.md
Add initial README content for `algolia_helper` and `algolia_helper_flutter`
=> chore: update `README.md`

helper_dart/CHANGELOG.md, helper_dart/pubspec.yaml, helper_flutter/CHANGELOG.md, helper_flutter/pubspec.yaml
=> chore: prepare release `0.1.1`

helper_dart/lib/src/query_builder.dart
Rewrite the build disjunctive faceting queries to avoid exception.
=> fix(QueryBuilder): build disjunctive faceting queries exception

helper_dart/CHANGELOG.md, helper_dart/pubspec.yaml, helper_flutter/CHANGELOG.md, helper_flutter/pubspec.yaml
=> chore: prepare release `0.1.2`

helper_dart/lib/src/facet_list.dart, helper_dart/lib/src/facet_list_internal.dart, helper_dart/lib/src/hits_searcher.dart, helper_dart/lib/src/hits_searcher_default.dart, helper_dart/lib/src/hits_searcher_internal.dart, helper_dart/test/facet_filter_test.dart, helper_dart/test/hits_searcher_test.dart
Split specification and implementation of `HitsSearcher` and `FacetList`.
=> refactor: `HitsSearcher` and `FacetList` spec and impl SoC

helper_dart/lib/src/facet_list_internal.dart, helper_dart/test/facet_filter_test.dart
Update `SearchState`s `disjunctiveFaceting` when `FacetList` is disjunctive.
=> feat(FacetList): update search state on disjunctive faceting 

helper_dart/lib/src/facet_list.dart, helper_dart/lib/src/hits_searcher.dart
* Fix `HitsSearcher`'s markdown
* Add `FacetList` documentation
=> doc: `HitsSearcher` and `FacetList`

README.md
- Added release stage
- Updated Stack overflow link
=> fix(readme): Added release stage

.github/workflows/lint_pr.yml
Add Lint PR step to check if the pull requests title conforms to semantic PR rules
Prevents merging pull requests with titles not conforming to semantic pr/commits.
=> chore: add pull request title lint step

.github/workflows/deployment.yml
Add possibility to trigger via GitHub action
=> chore: manual auto release

helper_dart/CHANGELOG.md, helper_dart/lib/src/lib_version.dart, helper_dart/pubspec.yaml, helper_flutter/CHANGELOG.md, helper_flutter/pubspec.yaml
=> chore: prepare next release 0.2.3

README.md, helper_dart/lib/src/lib_version.dart
Prepare release 0.3.0
All the pubspec and changelog changes are applied in the previous PRs
=> chore: prepare release 0.3.0

helper_dart/lib/src/disposable.dart, helper_dart/pubspec.lock, helper_dart/pubspec.yaml, helper_flutter/pubspec.lock, insights_dart/pubspec.lock, insights_dart/pubspec.yaml, pubspec.yaml
| BC breaks?      | no      |
This PR fixes all the issues affecting the Pub points of the packages since the version 0.3.0. 
With these changes, the Pub Points values for all three packages will be 130/130 again.
=> fix: Restore pub points

helper_dart/CHANGELOG.md, helper_dart/lib/src/lib_version.dart, helper_dart/pubspec.lock, helper_dart/pubspec.yaml, helper_flutter/CHANGELOG.md, helper_flutter/pubspec.lock, helper_flutter/pubspec.yaml, insights_dart/CHANGELOG.md, insights_dart/pubspec.yaml
Prepare release 0.3.1 
Fixes the issues with Pub points, restoring 130/130 for all the 3 packages.
=> chore: prepare release 0.3.1

CHANGELOG.md, helper_dart/CHANGELOG.md, helper_dart/pubspec.yaml, helper_flutter/CHANGELOG.md, helper_flutter/pubspec.yaml, insights_dart/CHANGELOG.md, insights_dart/pubspec.yaml
Prepare releases: 
- algolia_helper@0.3.3
- algolia_helper_flutter@0.3.3
- algolia_insights@0.1.2
=> chore(release): prepare releases

CHANGELOG.md, helper/CHANGELOG.md, helper/lib/src/lib_version.dart, helper/pubspec.yaml, insights/CHANGELOG.md, insights/README.md, insights/lib/src/lib_version.dart, insights/pubspec.yaml
- algolia_insights@0.2.0
- algolia_helper_flutter@0.4.0
Prepare releases Flutter Helper 0.4.0 and Insights 0.2.0
=> chore(release): prepare releases algolia_insights@0.2.0, algolia_helper_flutter@0.4.0

README.md
=> chore: move release stage to beta

CHANGELOG.md, helper/CHANGELOG.md, helper/lib/src/lib_version.dart, helper/pubspec.yaml, insights/CHANGELOG.md, insights/lib/src/lib_version.dart, insights/pubspec.yaml
- algolia_helper_flutter@0.4.1
- algolia_insights@0.2.1
Prepare patch release
=> chore(release): publish packages

CHANGELOG.md, README.md, analysis_options.yaml, helper/CHANGELOG.md, helper/lib/src/facet_list.dart, helper/lib/src/lib_version.dart, helper/lib/src/model/search_state.dart, helper/pubspec.yaml, insights/CHANGELOG.md, insights/lib/src/lib_version.dart, insights/pubspec.yaml, pubspec.yaml
- algolia_helper_flutter@1.0.0-pre
- algolia_insights@1.0.0-pre
| Need Doc update | yes   |
Prepare release 1.0.0-pre
=> chore(release): prepare release 1.0.0-pre

CHANGELOG.md, helper/CHANGELOG.md, helper/lib/src/lib_version.dart, helper/pubspec.yaml, insights/CHANGELOG.md, insights/lib/src/lib_version.dart, insights/pubspec.yaml
- algolia_helper_flutter@1.0.0
- algolia_insights@1.0.0
Prepare release 1.0.0
=> chore(release): prepare release 1.0.0

CONTRIBUTING.md, README.md
| Related Issue   |  |
This PR adds a contribution guide to help internal and external contributors set up the project and contribute effectively.
=> chore: add contribution guide

helper/lib/src/query_builder.dart, helper/test/query_builder_test.dart
| Bug fix?        |     no   |
| New feature?    | yes      |
| Related Issue   | N/A      |
| Need Doc update |     no   |
This PR updates how the queries are built before calling Algolia.
It now generates additional/auxiliary queries for refined disjunctive facets only. This optimizes the performance on Flutter implementations with a lot of registered facets.
=> feat(queryBuilder): remove aux queries for unrefined facets
